### ISSUE TITLE
[Feature] Offer the option to stop the stack and restart it after backup

### ISSUE THREAD

**Issue by Wobak** [hazzuk/compose-backupdate#13]
### Prerequisites

- [X] I have searched for duplicate or closed feature requests

### Proposal

Hello,

I am currently trying to implement this as you might have guessed from the other issue.

One thing I think could be valuable, especially for databases, would be an option to stop the stack, which could be a simple check of the currently running containers of the stack and then stopping them, and restarting them afterwards.

If you think it's valuable, I can start working on a PR for that.

### Motivation and context

I think some volumes can be backuped a bit for nothing if they contain in-transit data for DB for example.

**Comment by hazzuk** [comment]
Thank you for your feature request!

On your proposal:

> an option to stop the stack
> and restarting them afterwards.

Currently, all containers are [stopped](https://github.com/hazzuk/compose-backupdate/blob/main/backupdate.sh#L261) automatically before a backup to ensure the data saved is reliable. And only once the backup process is fully complete are the stacks containers [restarted](https://github.com/hazzuk/compose-backupdate/blob/main/backupdate.sh#L273).

Does this cover your proposal?

Or do you mean you want the script to restart/cycle the containers first before a backup because,
> they contain in-transit data for DB for example

**Comment by Wobak** [comment]
Hello ! 

I didn't see that you already implemented a stop/restart, that's great ! 
However, if I take one of my stacks, I can see we might be facing an issue in the check : 

```
root @ t340-2: /opt/docker/rss2email 32 # docker compose ls
[...]
rss2email           running(1)                   /opt/docker/rss2email/docker-compose.yml
[...]

root @ t340-2: /opt/docker/rss2email 33 # docker compose ps --filter "status=running" | grep -q "rss2email" ; echo $?
1
root @ t340-2: /opt/docker/rss2email 34 # docker compose ps --filter "status=running"
NAME                   IMAGE             COMMAND             SERVICE                CREATED        STATUS       PORTS
goeland-2024   slurdge/goeland   "/goeland daemon"   goeland-2024 2 months ago   Up 2 hours
```
So in that case your script says my stack is not running, but it actually is.

The other problem I have is that I have some stacks that might not be running all containers for xyz reason, and you script will try to restart the whole stack after backup, instead of just the ones that were running.

**Comment by hazzuk** [comment]
> script says my stack is not running, but it actually is.

Would you be able to fill out a bug report for this issue, and I might see if I can also recreate it.

> some stacks might not be running all containers
> script will try to restart the whole stack

This is a great point! The script does indeed currently assume an 'all or nothing' state when it comes to the containers being started/stopped.

I'm going to close this feature request, but I'd definitely recommend raising a new one with this specific edge case. And if you'd like to work on a PR for either issue I'd be happy to review it.
