### ISSUE TITLE
[Bug] function docker_stack_stop() considers the stack name to be part of the container name while it may not be

### ISSUE THREAD

**Issue by Wobak** [hazzuk/compose-backupdate#15]
### Prerequisites

- [X] I have searched for duplicate or closed issues

### What version are you using?

1.1.0

### Describe the issue

In its current version, the function [docker_stack_stop()](https://github.com/hazzuk/compose-backupdate/blob/main/backupdate.sh#L261) considers the stack to be running if the output of docker compose ps | grep $stackname returns 0

Unfortunately, this only works if container_name is not used and/or if the services name are generated with the stack name in them. 

### Expected behavior

If a docker compose stack is running, the function should return that it's running

### Actual behavior

Does return that the stack is not running for stacks where containers don't contain the stack name in them

### What operating system(s) are you seeing the issue on?

Linux

### Any additional notes

A good way to check if something is running would probably be to use either : 

```
stackname=rss2email ; docker compose ls --quiet --filter name=$stackname | grep -q $stackname && echo Stack running || echo Stack not running
Stack running
stackname=mangas ; docker compose ls --quiet --filter name=$stackname | grep -q $stackname && echo Stack running || echo Stack not running
Stack not running
```

Or if you want to use docker compose, then just run a : 
```
is_running=$(docker compose ps -q | wc -l) ; if [[ $is_running > 0 ]] ; then echo Stack is running; else echo Stack not running ; fi
```

**Comment by hazzuk** [comment]
Great find, was also able to replicate this:

1. Started a new Docker compose stack named `alpine`, with two containers `alpine` and `database-alpha`

(in the following steps I refer to alpine the container)

#### Original command
`docker compose ps --filter "status=running" | grep -q "alpine"; echo $?`

2. Only stopping `alpine` returns `1` ❌
3. Restarting `alpine` (all running) returns `0`
4. Stopping both returns `1`
5. Only restarting `alpine` returns `0`

<br>

#### Alternative command
`docker compose ls --quiet --filter "name=alpine" | grep -q "alpine"; echo $?`

2. Only stopping `alpine` returns `0` ✔️
3. Restarting `alpine` (all running) returns `0`
4. Stopping both returns `1`
5. Only restarting `alpine` returns `0`

**Comment by hazzuk** [comment]
A fix for this issue will be included in the next release.
