### ISSUE TITLE
[Feature] Track which containers are running before restarting the stack

### ISSUE THREAD

**Issue by Wobak** [hazzuk/compose-backupdate#16]
### Prerequisites

- [X] I have searched for duplicate or closed feature requests

### Proposal

Coming from https://github.com/hazzuk/compose-backupdate/issues/13

I think the script should check which containers are running and restart only those ones by adding the name of the running containers after the docker compose up -d command.

### Motivation and context

The script currently assumes it's a all or nothing when restarting a stack, where you can have sometimes containers meant for running a scheduled update at specific time that might not be running all the time (certbot updates, cron launching containers instead of being inside them and so on).

**Comment by hazzuk** [comment]
This feature will be included in the next release.
